#!/bin/bash
set -e

# ─────────────────────────────────────────────────────────────────
# Paperclip Docker — Setup Script
# Checks prerequisites, generates secrets, builds and starts.
# ─────────────────────────────────────────────────────────────────

echo ""
echo "  ╔══════════════════════════════════════╗"
echo "  ║       🐳 Paperclip Docker Setup      ║"
echo "  ╚══════════════════════════════════════╝"
echo ""

# ── 1. Check Docker ──────────────────────────────────────────────

echo "🔍 Checking prerequisites..."

if ! command -v docker &> /dev/null; then
    echo "❌ Docker is not installed."
    echo "   Install it with: curl -fsSL https://get.docker.com | sudo sh"
    exit 1
fi

if ! docker compose version &> /dev/null; then
    echo "❌ Docker Compose v2 is not installed."
    echo "   See: https://docs.docker.com/compose/install/"
    exit 1
fi

echo "✅ Docker $(docker --version | grep -oP '\d+\.\d+\.\d+')"
echo "✅ Docker Compose $(docker compose version --short)"
echo ""

# ── 2. Generate .env ─────────────────────────────────────────────

if [ -f .env ]; then
    echo "📄 .env file already exists — skipping generation."
    echo "   Delete it and re-run setup.sh to regenerate."
else
    echo "🔑 Generating .env file with secure secrets..."

    BETTER_AUTH_SECRET=$(openssl rand -hex 32)
    POSTGRES_PASSWORD=$(openssl rand -hex 16)

    cat > .env << EOF
# ═══════════════════════════════════════════════════════════════
# Paperclip Docker — Generated by setup.sh
# ═══════════════════════════════════════════════════════════════

# ── Required ──────────────────────────────────────────────────
BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
PAPERCLIP_PUBLIC_URL=https://paperclip.example.com

# ── Database ──────────────────────────────────────────────────
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# ── AI Agent API Keys (optional) ──────────────────────────────
ANTHROPIC_API_KEY=
OPENAI_API_KEY=
EOF

    chmod 600 .env

    echo "✅ .env created with generated secrets"
    echo ""
    echo "   ⚠️  Edit .env and set PAPERCLIP_PUBLIC_URL to your domain"
    echo "   ⚠️  Add your AI provider API keys (ANTHROPIC_API_KEY, OPENAI_API_KEY)"
fi

echo ""

# ── 3. Build and start ───────────────────────────────────────────

echo "🐳 Building Paperclip Docker image..."
echo "   ☕ This clones and compiles from source — it may take a few minutes."
echo ""

docker compose build

echo ""
echo "🚀 Starting Paperclip..."

docker compose up -d

echo ""
echo "  ╔══════════════════════════════════════╗"
echo "  ║          ✅ Setup complete!          ║"
echo "  ╚══════════════════════════════════════╝"
echo ""
echo "  📋 View logs:     docker compose logs -f server"
echo "  ⏹️  Stop:          docker compose down"
echo "  🔄 Restart:       docker compose restart server"
echo ""
echo "  🌐 Paperclip is running at http://127.0.0.1:3100"
echo "     Connect a reverse proxy to expose it on your domain."
echo ""
